export const SUBSCRIPTION_RENEWAL_RATE = [
    "MONTHLY_RENEWAL_EVERY_THREE_MINUTES",
    "MONTHLY_RENEWAL_EVERY_FIVE_MINUTES",
    "MONTHLY_RENEWAL_EVERY_FIFTEEN_MINUTES",
    "MONTHLY_RENEWAL_EVERY_THIRTY_MINUTES",
    "MONTHLY_RENEWAL_EVERY_ONE_HOUR",
];